name: Build and upload binaries to release

on:
  repository_dispatch:
    types: [tag-created]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: wowp.zip
            asset_name: wowp-linux-amd64.zip
          - os: macos-latest
            artifact_name: wowp.zip
            asset_name: wowp-macos-amd64.zip
          - os: windows-latest
            artifact_name: wowp.zip
            asset_name: wowp-win-amd64.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        shell: bash
        run: |
          cargo build --release --locked
          7z a wowp.zip event_templates target/release/wowp target/release/wowp.exe
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.client_payload.new_version }}
